Enabled server-side Secure ETCD and Secure GRPC
kubearmor/kvm-service pull request #28
Opened 2021-12-07 09:31 UTC by seswarrajan

2021-12-09 15:54 UTC, nyrahul requested changes
Thanks, please check the comments.

2021-12-09 15:54 UTC, nyrahul commented on src/service/server/server.go
> +		kg.Errf("Failed to setup TLS: %v", err)
return needed here.

2021-12-09 15:54 UTC, nyrahul commented on src/service/server/server.go
>  		kg.Err("Failed to serve gRPCServer is null")
Return needed here.

2021-12-13 05:03 UTC, seswarrajan commented
Closing this PR as this is a duplicate of https://github.com/kubearmor/kvm-service/pull/30

https://github.com/kubearmor/kvm-service/pull/30 is the updated PR

2021-12-13 05:03 UTC, closed without merging