systemd packaging for kvmservice
kubearmor/kvm-service pull request #55
Opened 2022-04-13 06:16 UTC by seswarrajan

2022-04-18 05:09 UTC, nyrahul requested changes

2022-04-18 05:09 UTC, nyrahul commented on src/service/nfpm.yaml
> +homepage: "https://kubearmor.com"
```suggestion
homepage: "https://kubearmor.io"
```

2022-04-18 10:16 UTC, daemon1024 reviewed
A few questions:
1. Does this expect kubearmor to be running already? or will it start kubearmor (in docker I presume) using genScript?
		- Will we need to add docker dependency as well?
2. CI for this will be handled in this PR or a seperate one?
3. Documentation to test out the changes?4.

2022-04-18 11:14 UTC, seswarrajan commented
> A few questions:
> 
> 1. Does this expect kubearmor to be running already? or will it start kubearmor (in docker I presume) using genScript?
>    - Will we need to add docker dependency as well?
@daemon1024 kvmservice is on control-plane VM and does not require Kubearmor to be running already.  kvm-service is not dependent on kubearmor.

> 2. CI for this will be handled in this PR or a seperate one?
Planning to handle in separate PR. Please suggest @daemon1024 and @nyrahul  

> 3. Documentation to test out the changes?4.
Yet to be done.

2022-04-18 11:23 UTC, daemon1024 commented
> >      @daemon1024 kvmservice is on control-plane VM and does not require Kubearmor to be running already.  kvm-service is not dependent on kubearmor.

Makes sense. Reading the docs, only dependency is etcd. We should handle it's dependency and also start the etcd service as part of preinstall script if not already running. WDYT?

> > 2. CI for this will be handled in this PR or a seperate one?

It's fine either way imo.

2022-04-18 12:57 UTC, seswarrajan commented
> > > ```
> > >  @daemon1024 kvmservice is on control-plane VM and does not require Kubearmor to be running already.  kvm-service is not dependent on kubearmor.
> > > ```
> 
> Makes sense. Reading the docs, only dependency is etcd. We should handle it's dependency and also start the etcd service as part of preinstall script if not already running. WDYT?
> 
> > > 2. CI for this will be handled in this PR or a seperate one?
> 
> It's fine either way imo.



> We should handle it's dependency and also start the etcd service as part of preinstall script if not already running. WDYT?
@daemon1024 I suggest to throw an error and notify user to install ETCD in their own method of installation. 
@nyrahul Please suggest a solution here,

2022-04-21 04:03 UTC, nyrahul approved these changes

2022-04-21 04:04 UTC, merged